---
title: "Homework 2"
author: "Melissa Wong"
date: "4/25/2021"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rethinking)
library(brms)
library(bayesplot)
library(tidybayes)
library(RColorBrewer)

# mc-stan options
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)

# mean centered weight and height
data(Howell1)

df <- Howell1[Howell1$age >= 18,]
df$c_height <- scale(df$height, scale=FALSE)
df$c_weight <- scale(df$weight, scale=FALSE)
```

# Problem 1

## Using `rethinking::quap`
```{r quapmdl}
mdl1 <- quap(
  alist(
    height ~ dnorm(mu, sigma),
    mu <- a + b * c_weight,
    a ~ dnorm(178, 20),
    b ~ dnorm(0,1),
    sigma ~ dunif(0, 50)
  ),
  data = df
)

precis(extract.samples(mdl1))

# Predict for following weights
wbar <- attr(df$c_weight, 'scaled:center')
weight <- c(45, 40, 65, 31)
mu <- link(mdl1, data=data.frame(c_weight = weight - wbar ))

# Expected values of height
cbind(weight, 
           expected_height = apply(mu, 2, mean),
           t(apply(mu, 2, PI))) %>%
  knitr::kable()

```

## Using `brms::brm` 

```{r brmsmdl}
mdl1.2 <- brm(height ~ c_weight, data=df, family=gaussian(),
            prior=c(set_prior("normal(178, 20)", class="Intercept"),
                    set_prior("normal(0, 1)", class="b", coef = "c_weight"),
                    # mc-stan has problems converging with uniform prior, use half-cauchy prior instead
                    set_prior("cauchy(0,1)", class="sigma")))

summary(mdl1.2, prob=0.89)

# Diagnostics
mcmc_rank_overlay(mdl1.2)
pp_check(mdl1.2)

# Posterior Predictions
wbar <- attr(df$c_weight, 'scaled:center')
weight <- c(45, 40, 65, 31)

fitted(mdl1.2, newdata = data.frame(c_weight = weight - wbar), scale="response", 
       summary=TRUE, probs=c(0.055, 0.945))

# Equivalent w/tidybayes
add_fitted_draws(newdata=data.frame(c_weight = weight - wbar),
                 mdl1.2, value="height") %>%
  group_by(.row) %>%
  summarize(expected_height = mean(height),
            `Q5.5` = quantile(height, 0.055),
            `Q94.5` = quantile(height, 0.945))

```

# Problem 2

```{r}
df <- Howell1
df$log_wt <- log(df$weight)
ggplot(df) +
  geom_point(mapping=aes(x=log_wt, height))
```
```{r}
log_wt_bar <- mean(df$log_wt)
# Fit linear model
mdl2 <- quap(
  alist(
    height ~ dnorm(mu, sigma),
    mu <- a + b * (log_wt-log_wt_bar),
    a ~ dnorm(178, 20),
    b ~ dnorm(0,25),
    sigma ~ dunif(0, 50)
  ),
  data = df
)

precis(mdl2)

mu <- apply(link(mdl2), 2, mean)
ggplot(mapping=aes(x=df$log_wt)) +
  geom_point(mapping=aes(y=df$height, color="observed"), alpha=0.5) +
  geom_point(mapping=aes(y=mu, color="predicted"),
             alpha=0.5) +
  # Use colorblind-friendly palette
  scale_colour_brewer(palette = "Set2")
```

# Problem 3

```{r polymdl}
# Polynomial model
df <- Howell1
summary(df)

# Plot prior predictive distribution
N <- 20
df <- data.frame(
  a = rnorm(N, 178, 20),
  b1 = rlnorm(N, 0, 1),
  b2 = rnorm(N, 0, 1),
  b3 = rnorm(N, 0, 1)
)

wt <- seq(-2, 2, length.out=25)
df1 <- cbind(df, t(apply(df, 1, function(row) row[1] + row[2] * wt + row[3] * wt^2 + row[4]*wt^3)))
df1$iteration <- as.factor(1:N)

df1 %>%
  pivot_longer(cols=-c("a", "b1", "b2", "b3", "iteration"), 
               values_to = "height",
               names_to="weight") %>%
ggplot() +
  geom_line(mapping=aes(x=as.numeric(weight), y=height,
                        group=iteration), alpha=0.5)
```

The priors from the book yield a reasonable range of prior predictive distributions.