---
title: Assignment 7
author: "Melissa Wong"
date: \today
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r libraries, results='hide', message=FALSE, warning=FALSE}

library(tidyverse)
library(RColorBrewer)
#library(rethinking)
library(gridExtra)
library(tidybayes)
library(bayesplot)
#library(rstan)
library(dagitty)
library(here)
library(brms)
library(cmdstanr)
```

```{r options}
options("scipen" = 1, "digits" = 4)

#knitr::opts_chunk$set(echo = FALSE)
#knitr::opts_chunk$set(message = FALSE)
#knitr::opts_chunk$set(warning = FALSE)
#knitr::opts_chunk$set(out.width = "50%")
knitr::opts_chunk$set(fig.align = "center")

# Set Default ggplot palette
options(ggplot2.discrete.color=brewer.pal(8, "Dark2"))
options(ggplot2.discrete.fill=brewer.pal(8, "Dark2"))

set_cmdstan_path(here("../.cmdstanr/cmdstan-2.27.0"))
ncores <- min(4, parallel::detectCores()-1)

# Set brms backend to cmdstanr
options(brms.backend="cmdstanr")
```

# Problem 1
 
```{r}
data("Trolley")

df <- Trolley %>%
  select(response, action, intention, contact, edu, age) %>% 
  mutate(edu = fct_relevel(edu, "Elementary School",
                           "Middle School",
                           "Some High School",
                           "High School Graduate",
                           "Some College",
                           "Bachelor's Degree",
                           "Master's Degree",
                           "Graduate Degree"))

df$edu <- factor(df$edu, ordered = TRUE)
```



```{r include=FALSE, eval=FALSE}

# logit link
mdl_logit <- brm(response ~  1,
           data=df,
           family=cumulative(link="logit"),
           chains=4,
           cores=ncores,
           file_refit = "on_change",
           file = here("homework/mdl7-logit.rds")
           )


# Calculate cumulative log odds
cum_log_odds <- logit_scaled(cumsum(table(df$response))/length(df$response))

cbind(posterior_summary(mdl_logit, pars="b_Intercept"),
      observed = cum_log_odds[1:6])

# probit link

mdl_probit <- brm(response ~  1,
           data=df,
           family=cumulative(link="probit"),
           chains=4,
           cores=ncores,
           file_refit = "on_change",
           file = here("homework/mdl7-probit.rds")
           )

# Calculate cumulative Z-scores
cum_probit <- qnorm(cumsum(table(df$response))/length(df$response))


cbind(posterior_summary(mdl_probit, pars="b_Intercept"),
      observed = cum_probit[1:6])
```

```{r}
G <- dagitty("dag{ 
             response <- age -> edu;
             edu -> response;
             intention -> response;
             contact -> response;
             action -> response;
             }")

plot(graphLayout(G))

 adjustmentSets(G, outcome="response", exposure="edu",
                effect="direct")
```
Need to condition on _age_ to determine what, if any, direct causal effect _edu_ has on _response_.

## logit link

```{r results='hide'}

mdl1 <- brm(response ~  age + edu + intention + action + contact + action:intention + contact:intention,
           data=df,
           family=cumulative(link="logit"),
           chains=4,
           cores=ncores,
           file_refit = "on_change",
           file = here("homework/mdl7-1.rds")
           )

# Treat edu as monotonic ordered factor
# See https://cran.r-project.org/web/packages/brms/vignettes/brms_monotonic.html
mdl2 <- brm(response ~  age + mo(edu) + intention + action + contact + action:intention + contact:intention,
           data=df,
           family=cumulative(link="logit"),
           chains=4,
           cores=ncores,
           file_refit = "on_change",
           file = here("homework/mdl7-2.rds")
           )
#stancode(mdl)
```



```{r}
# Note: Intercept terms are when predictors are mean centered
# For our purposes, we care about b_Intercept terms in the 
# plots below
# See https://discourse.mc-stan.org/t/b-intercept-and-intercept-how-are-they-related/12933/4 
mcmc_rank_overlay(mdl1, regex_pars=c("^b_", "sigma"))
```


```{r}
summary(mdl1)
```

Note: _disc_ is the discrimination parameter.

```{r}
mcmc_plot(mdl1, type="intervals",
          pars=c("^b_"),
          prob=0.5, prob_outer=0.95,
          point_est="median")
```


```{r}
conditional_effects(mdl1, categorical=TRUE) 
```

```{r}
loo(mdl1, mdl2)
```

## probit link

```{r results='hide'}

mdl1b <- brm(response ~  age + edu + intention + action + contact + action:intention + contact:intention,
           data=df,
           family=cumulative(link="probit"),
           chains=4,
           cores=ncores,
           file_refit = "on_change",
           file = here("homework/mdl7-1b.rds")
           )

#stancode(mdl)
summary(mdl1b)

mcmc_rank_overlay(mdl1b, regex_pars=c("^b_", "sigma"))

mcmc_plot(mdl1b, type="intervals",
          pars=c("^b_"),
          prob=0.5, prob_outer=0.95,
          point_est="median")

plot(conditional_effects(mdl1b, categorical = TRUE)) 
```
```{r include=FALSE, evalu=FALSE}
# Create conditional effects plot by hand
add_epred_draws(mdl1b, 
                newdata=data.frame(age=seq(10, 72),
                                        edu="Elementary School")) %>%
  ggplot(aes(x=age, color=.category)) +
  stat_lineribbon(aes(y = .epred),
                  .width=0.95) 
  
```

